### ISSUE TITLE
Install extension adds `@<version>` at in the extension folder

### ISSUE THREAD

**Issue by huchenlei** [Comfy-Org/manager-core#9]
The `@<version>` suffix in extension folder breaks the loading of frontend extensions.

**Comment by ltdrdata** [comment]
> The `@<version>` suffix in extension folder breaks the loading of frontend extensions.

I think it would be better to use an escaped version of module_name here instead of using it directly.
https://github.com/comfyanonymous/ComfyUI/blob/d9f90965c8601b671faca9c8784b529e389c49aa/nodes.py#L2027

What do you think?
